export type SupplierProfileInput = {
  companyName?: unknown;
  firstName?: unknown;
  lastName?: unknown;
  email?: unknown;
  phone?: unknown;
  tradeLicenseNumber?: unknown;
  contactPerson?: unknown;
  designation?: unknown;
  supplierContactPhone?: unknown;
  tradeLicenseImageUrl?: unknown;
  vatTrnNumber?: unknown;
  vatTrnImageUrl?: unknown;
  supplierIdentityDocumentType?: unknown;
  emiratesIdPassportUrl?: unknown;
  emiratesIdBackUrl?: unknown;
  passportAddressUrl?: unknown;
  passportVisaFrontUrl?: unknown;
  bankIban?: unknown;
  bankAccountProofUrl?: unknown;
  marketplaceAgreementAccepted?: unknown;
  addressLine1?: unknown;
  addressLine2?: unknown;
  city?: unknown;
  state?: unknown;
  postalCode?: unknown;
  country?: unknown;
};

export type SupplierProfileRecord = {
  id: string;
  publicId: string;
  supplierPublicId: string | null;
  companyName: string | null;
  firstName: string | null;
  lastName: string | null;
  email: string | null;
  emailVerifiedAt: string | null;
  phone: string | null;
  tradeLicenseNumber: string | null;
  contactPerson: string | null;
  designation: string | null;
  supplierContactPhone: string | null;
  supplierContactPhoneVerifiedAt: string | null;
  tradeLicenseImageUrl: string | null;
  vatTrnNumber: string | null;
  vatTrnImageUrl: string | null;
  supplierIdentityDocumentType: string | null;
  emiratesIdPassportUrl: string | null;
  emiratesIdBackUrl: string | null;
  passportAddressUrl: string | null;
  passportVisaFrontUrl: string | null;
  bankIban: string | null;
  bankAccountProofUrl: string | null;
  marketplaceAgreementAcceptedAt: string | null;
  mobileVerifiedAt: string | null;
  avatarUrl: string | null;
  addressLine1: string | null;
  addressLine2: string | null;
  city: string | null;
  state: string | null;
  postalCode: string | null;
  country: string | null;
  supplierApprovalStatus: string;
  supplierApprovalRejectionReason: string | null;
  createdAt: string;
  updatedAt: string;
};

export type SupplierVerificationResponse = {
  ok: true;
  message: string;
  verificationLink?: string;
};
